import { randomUUID } from 'node:crypto';
import { rename, unlink, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { Redactor } from '@lnwjud/audit';
import type { LogLine, TunnelStatus } from '@lnwjud/ipc-contracts';

const execFileAsync = promisify(execFile);
const MAX_ENTRIES = 200;
const MAX_TEXT = 512;
const MAX_IDS = 50;
const redactor = new Redactor();

export type IncidentClassification = 'local_tool_failed' | 'tunnel_disconnected' | 'remote_turn_stopped' | 'healthy_or_inconclusive';
export type TunnelHealthState = 'live' | 'unhealthy' | 'unavailable' | 'unknown';
export interface IncidentHealth { readonly state: TunnelHealthState; readonly message: string | null; }
type IncidentLine = Pick<LogLine, 'source' | 'text' | 'timestamp' | 'correlation'>;
export interface IncidentEvidence { readonly triggeredByUser: boolean; readonly appVersion: string; readonly tunnelClientVersion: string | null; readonly tunnelClientVersionReason?: string | null; readonly tunnel: Pick<TunnelStatus, 'state' | 'source' | 'message'> & { readonly health: IncidentHealth }; readonly updaterEvents: readonly string[]; readonly logLines: readonly IncidentLine[]; readonly collectProcessTree?: (pids: readonly number[]) => Promise<readonly IncidentProcess[]>; readonly collectListeners?: (pids: readonly number[]) => Promise<readonly IncidentListener[]>; }
export interface IncidentProcess { readonly pid: number; readonly parentPid: number | null; readonly executable: string; }
export interface IncidentListener { readonly pid: number; readonly address: string; readonly port: number; readonly owner?: string; }
export interface IncidentCall { readonly callId: string; readonly toolName: string | null; readonly resultCode: 'SUCCESS' | 'FAILED' | 'FATAL' | 'UNKNOWN' | null; readonly incomplete: boolean; readonly startedWithoutCompletion: boolean; readonly completionWithoutStart: boolean; }
export interface IncidentReport { readonly schemaVersion: 1; readonly capturedAt: string; readonly appVersion: string; readonly tunnelClientVersion: string | null; readonly tunnelClientVersionReason: string | null; readonly classification: IncidentClassification; readonly classificationReasons: readonly string[]; readonly updaterEventTail: readonly string[]; readonly tunnel: { readonly state: TunnelStatus['state']; readonly source: TunnelStatus['source']; readonly message: string | null; readonly instanceIds: readonly string[]; readonly requestIds: readonly string[]; readonly health: IncidentHealth; }; readonly mcpCalls: readonly IncidentCall[]; readonly tunnelLogTail: readonly { readonly timestamp: string; readonly text: string }[]; readonly processTree: { readonly available: boolean; readonly entries: readonly { readonly pid: number; readonly parentPid: number | null; readonly executable: string }[]; readonly error?: string; }; readonly tcpListeners: { readonly available: boolean; readonly entries: readonly { readonly pid: number; readonly address: string; readonly port: number; readonly owner: string | null }[]; readonly error?: string; }; }

export function classifyIncident(evidence: Pick<IncidentEvidence, 'triggeredByUser' | 'tunnel' | 'logLines'>): { readonly classification: IncidentClassification; readonly reasons: readonly string[] } {
  const latestTerminal = pairMcpCalls(evidence.logLines).filter((call) => !call.incomplete && call.resultCode !== null).at(-1);
  if (latestTerminal?.resultCode === 'FAILED' || latestTerminal?.resultCode === 'FATAL') return { classification: 'local_tool_failed', reasons: ['latest_structured_mcp_terminal_failed'] };
  const tunnelText = evidence.logLines.filter((line) => line.source === 'tunnel').map((line) => line.text).join('\n');
  if (evidence.tunnel.state === 'stopped' || evidence.tunnel.state === 'error' || evidence.tunnel.health.state === 'unhealthy' || /\b(TTL reached|stdio(?: MCP)? (?:command|process)?\s*(?:exited|closed|terminated)|requesting tunnel-client shutdown|shutting down|shutdown|stopped|disconnect(?:ed|ing)?)\b/i.test(`${evidence.tunnel.message ?? ''}\n${tunnelText}`)) return { classification: 'tunnel_disconnected', reasons: ['explicit_tunnel_disconnect_evidence'] };
  if (evidence.triggeredByUser && latestTerminal?.resultCode === 'SUCCESS' && evidence.tunnel.state === 'running' && evidence.tunnel.health.state === 'live') return { classification: 'remote_turn_stopped', reasons: ['manual_capture_after_structured_success_with_live_tunnel'] };
  return { classification: 'healthy_or_inconclusive', reasons: [evidence.tunnel.state === 'starting' ? 'tunnel_starting' : evidence.tunnel.health.state === 'unavailable' ? 'tunnel_health_unavailable' : 'insufficient_non_conflicting_evidence'] };
}

export function pairMcpCalls(lines: readonly IncidentLine[]): readonly IncidentCall[] {
  const pending = new Map<string, { toolName: string }[]>(); const calls: IncidentCall[] = [];
  for (const line of lines) { const c = line.correlation; if (c?.kind !== 'mcp') continue; const callId = safe(c.callId); if (c.phase === 'started') { const queue = pending.get(callId) ?? []; queue.push({ toolName: safe(c.toolName) }); pending.set(callId, queue); continue; } const start = pending.get(callId)?.shift(); calls.push({ callId, toolName: start?.toolName ?? safe(c.toolName), resultCode: c.resultCode, incomplete: start === undefined, startedWithoutCompletion: false, completionWithoutStart: start === undefined }); }
  for (const [callId, starts] of pending) for (const start of starts) calls.push({ callId, toolName: start.toolName, resultCode: null, incomplete: true, startedWithoutCompletion: true, completionWithoutStart: false });
  return calls.slice(-MAX_ENTRIES);
}

export function parseTunnelCorrelations(lines: readonly IncidentLine[]): { readonly instanceIds: readonly string[]; readonly requestIds: readonly string[] } {
  const instanceIds = new Set<string>(); const requestIds = new Set<string>();
  for (const line of lines.slice(-MAX_ENTRIES)) { if (line.source !== 'tunnel') continue; if (line.correlation?.kind === 'tunnel') { if (line.correlation.instanceId !== undefined) instanceIds.add(safe(line.correlation.instanceId)); if (line.correlation.requestId !== undefined) requestIds.add(safe(line.correlation.requestId)); } for (const match of line.text.matchAll(/\b(?:instance[_-]?id|instance)[=:]([A-Za-z0-9._:-]{1,128})/ig)) instanceIds.add(safe(match[1]!)); for (const match of line.text.matchAll(/\b(?:request[_-]?id|request)[=:]([A-Za-z0-9._:-]{1,128})/ig)) requestIds.add(safe(match[1]!)); }
  return { instanceIds: [...instanceIds].slice(-MAX_IDS), requestIds: [...requestIds].slice(-MAX_IDS) };
}

export async function buildIncidentReport(evidence: IncidentEvidence): Promise<IncidentReport> { const classification = classifyIncident(evidence); const pids = relevantPids(evidence.logLines); const [processTree, tcpListeners] = await Promise.all([collectProcesses(evidence.collectProcessTree, pids), collectListeners(evidence.collectListeners, pids)]); const correlations = parseTunnelCorrelations(evidence.logLines); return { schemaVersion: 1, capturedAt: new Date().toISOString(), appVersion: safe(evidence.appVersion), tunnelClientVersion: evidence.tunnelClientVersion === null ? null : safe(evidence.tunnelClientVersion), tunnelClientVersionReason: evidence.tunnelClientVersionReason === undefined || evidence.tunnelClientVersionReason === null ? null : safe(evidence.tunnelClientVersionReason), classification: classification.classification, classificationReasons: classification.reasons.map(safe), updaterEventTail: evidence.updaterEvents.slice(-MAX_ENTRIES).map(safe), tunnel: { state: evidence.tunnel.state, source: evidence.tunnel.source, message: evidence.tunnel.message === null ? null : safe(evidence.tunnel.message), ...correlations, health: { state: evidence.tunnel.health.state, message: evidence.tunnel.health.message === null ? null : safe(evidence.tunnel.health.message) } }, mcpCalls: pairMcpCalls(evidence.logLines), tunnelLogTail: evidence.logLines.filter((line) => line.source === 'tunnel').slice(-MAX_ENTRIES).map((line) => ({ timestamp: safe(line.timestamp), text: safe(line.text) })), processTree, tcpListeners }; }
export interface IncidentExportOptions { readonly choosePath: () => Promise<string | null>; readonly writeAtomically: (filePath: string, content: string) => Promise<void>; }
export async function exportIncidentReport(evidence: IncidentEvidence, options: IncidentExportOptions): Promise<{ readonly exported: boolean; readonly cancelled: boolean; readonly classification: IncidentClassification; readonly capturedAt: string | null }> { const report = await buildIncidentReport(evidence); const filePath = await options.choosePath(); if (filePath === null) return { exported: false, cancelled: true, classification: report.classification, capturedAt: null }; await options.writeAtomically(filePath, JSON.stringify(report, null, 2) + '\n'); return { exported: true, cancelled: false, classification: report.classification, capturedAt: report.capturedAt }; }
export async function atomicWrite(filePath: string, content: string): Promise<void> { const temp = `${filePath}.${randomUUID()}.tmp`; try { await writeFile(temp, content, { encoding: 'utf8', flag: 'wx' }); await rename(temp, filePath); } catch (error) { await unlink(temp).catch(() => undefined); throw error; } }
export async function collectRelevantProcessTree(pids: readonly number[]): Promise<readonly IncidentProcess[]> { if (pids.length === 0) return []; const clause = pids.map((pid) => `$_.ProcessId -eq ${pid}`).join(' -or '); const { stdout } = await execFileAsync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', `Get-CimInstance Win32_Process -ErrorAction Stop | Where-Object { ${clause} } | Select-Object ProcessId,ParentProcessId,Name | ConvertTo-Json -Compress`], { windowsHide: true, timeout: 3_000, encoding: 'utf8' }); return parseRows(stdout).map((row) => ({ pid: number(row.ProcessId), parentPid: number(row.ParentProcessId), executable: safe(typeof row.Name === 'string' ? row.Name : 'unknown') })); }
export async function collectRelevantListeners(pids: readonly number[]): Promise<readonly IncidentListener[]> { if (pids.length === 0) return []; const clause = pids.map((pid) => `$_.OwningProcess -eq ${pid}`).join(' -or '); const { stdout } = await execFileAsync('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', `Get-NetTCPConnection -State Listen -ErrorAction Stop | Where-Object { ${clause} } | Select-Object OwningProcess,LocalAddress,LocalPort | ConvertTo-Json -Compress`], { windowsHide: true, timeout: 3_000, encoding: 'utf8' }); return parseRows(stdout).map((row) => ({ pid: number(row.OwningProcess), address: safe(typeof row.LocalAddress === 'string' ? row.LocalAddress : 'unknown'), port: number(row.LocalPort) })); }
function relevantPids(lines: readonly IncidentLine[]): number[] { const pids = new Set<number>(); for (const line of lines.slice(-MAX_ENTRIES)) if (line.correlation?.kind === 'tunnel' && typeof line.correlation.pid === 'number' && Number.isInteger(line.correlation.pid)) pids.add(line.correlation.pid); return [...pids].slice(-MAX_IDS); }
async function collectProcesses(collector: IncidentEvidence['collectProcessTree'], pids: readonly number[]): Promise<IncidentReport['processTree']> { if (collector === undefined) return { available: false, entries: [], error: 'unavailable' }; try { return { available: true, entries: (await collector(pids)).slice(0, MAX_ENTRIES).map((entry) => ({ pid: entry.pid, parentPid: entry.parentPid, executable: safe(entry.executable) })) }; } catch (error) { return { available: false, entries: [], error: safe(error instanceof Error ? error.message : String(error)) }; } }
async function collectListeners(collector: IncidentEvidence['collectListeners'], pids: readonly number[]): Promise<IncidentReport['tcpListeners']> { if (collector === undefined) return { available: false, entries: [], error: 'unavailable' }; try { return { available: true, entries: (await collector(pids)).slice(0, MAX_ENTRIES).map((entry) => ({ pid: entry.pid, address: safe(entry.address), port: entry.port, owner: entry.owner === undefined ? null : safe(entry.owner).split(/\s+/)[0] ?? null })) }; } catch (error) { return { available: false, entries: [], error: safe(error instanceof Error ? error.message : String(error)) }; } }
function safe(value: string): string { const base = redactor.redact(value); return (typeof base === 'string' ? base : '').replace(/("(?:authorization|api[_-]?key|apikey|token|secret|password)"\s*:\s*")[^"]*(")/ig, '$1[REDACTED]$2').replace(/\b(?:authorization|x-api-key|api[_-]?key|apikey|token|secret|password)\s*[:=]\s*(?:(?:basic|bearer)\s*)?[^\r\n,;}\]]+/ig, (match) => `${match.split(/[:=]/)[0]}=[REDACTED]`).replace(/\b(?:basic|bearer)\s+[^\s,;]+/ig, '[REDACTED]').replace(/([?&](?:token|api[_-]?key|apikey|secret|password)=)[^&#\s]+/ig, '$1[REDACTED]').replace(/sk-[A-Za-z0-9_-]+/ig, '[REDACTED]').slice(0, MAX_TEXT); }
function parseRows(raw: string): Record<string, unknown>[] { try { const parsed: unknown = JSON.parse(raw || '[]'); return (Array.isArray(parsed) ? parsed : [parsed]).filter((value): value is Record<string, unknown> => typeof value === 'object' && value !== null).slice(0, MAX_ENTRIES); } catch { return []; } }
function number(value: unknown): number { return typeof value === 'number' && Number.isFinite(value) ? value : 0; }
